/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PagamentoDemoPreviewRouteImport } from './routes/pagamento.demo-preview'
import { Route as PagamentoOrderIdRouteImport } from './routes/pagamento.$orderId'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminCheckoutsIndexRouteImport } from './routes/admin.checkouts.index'
import { Route as AdminCheckoutsIdRouteImport } from './routes/admin.checkouts.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PagamentoDemoPreviewRoute = PagamentoDemoPreviewRouteImport.update({
  id: '/pagamento/demo-preview',
  path: '/pagamento/demo-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoOrderIdRoute = PagamentoOrderIdRouteImport.update({
  id: '/pagamento/$orderId',
  path: '/pagamento/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckoutsIndexRoute = AdminCheckoutsIndexRouteImport.update({
  id: '/checkouts/',
  path: '/checkouts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckoutsIdRoute = AdminCheckoutsIdRouteImport.update({
  id: '/checkouts/$id',
  path: '/checkouts/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/pagamento/$orderId': typeof PagamentoOrderIdRoute
  '/pagamento/demo-preview': typeof PagamentoDemoPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/checkouts/$id': typeof AdminCheckoutsIdRoute
  '/admin/checkouts/': typeof AdminCheckoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$slug': typeof CSlugRoute
  '/pagamento/$orderId': typeof PagamentoOrderIdRoute
  '/pagamento/demo-preview': typeof PagamentoDemoPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/admin/checkouts/$id': typeof AdminCheckoutsIdRoute
  '/admin/checkouts': typeof AdminCheckoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/pagamento/$orderId': typeof PagamentoOrderIdRoute
  '/pagamento/demo-preview': typeof PagamentoDemoPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/checkouts/$id': typeof AdminCheckoutsIdRoute
  '/admin/checkouts/': typeof AdminCheckoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/c/$slug'
    | '/pagamento/$orderId'
    | '/pagamento/demo-preview'
    | '/admin/'
    | '/admin/checkouts/$id'
    | '/admin/checkouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/$slug'
    | '/pagamento/$orderId'
    | '/pagamento/demo-preview'
    | '/admin'
    | '/admin/checkouts/$id'
    | '/admin/checkouts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/c/$slug'
    | '/pagamento/$orderId'
    | '/pagamento/demo-preview'
    | '/admin/'
    | '/admin/checkouts/$id'
    | '/admin/checkouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CSlugRoute: typeof CSlugRoute
  PagamentoOrderIdRoute: typeof PagamentoOrderIdRoute
  PagamentoDemoPreviewRoute: typeof PagamentoDemoPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pagamento/demo-preview': {
      id: '/pagamento/demo-preview'
      path: '/pagamento/demo-preview'
      fullPath: '/pagamento/demo-preview'
      preLoaderRoute: typeof PagamentoDemoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$orderId': {
      id: '/pagamento/$orderId'
      path: '/pagamento/$orderId'
      fullPath: '/pagamento/$orderId'
      preLoaderRoute: typeof PagamentoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkouts/': {
      id: '/admin/checkouts/'
      path: '/checkouts'
      fullPath: '/admin/checkouts/'
      preLoaderRoute: typeof AdminCheckoutsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkouts/$id': {
      id: '/admin/checkouts/$id'
      path: '/checkouts/$id'
      fullPath: '/admin/checkouts/$id'
      preLoaderRoute: typeof AdminCheckoutsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCheckoutsIdRoute: typeof AdminCheckoutsIdRoute
  AdminCheckoutsIndexRoute: typeof AdminCheckoutsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCheckoutsIdRoute: AdminCheckoutsIdRoute,
  AdminCheckoutsIndexRoute: AdminCheckoutsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CSlugRoute: CSlugRoute,
  PagamentoOrderIdRoute: PagamentoOrderIdRoute,
  PagamentoDemoPreviewRoute: PagamentoDemoPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
